### ISSUE TITLE
where is text file?

### ISSUE THREAD

**Issue by ghost** [BoPengGit/LDA-Doc2Vec-example-with-PCA-LDAvis-visualization#1]
Hello. I want to test this project.

But, I can't find "tokens_after_lemmas_and_rm_stopwords.txt" file.

where is it?

thank you.

**Comment by BoPengGit** [comment]
Hi Samjin,

The data files are private and company property so it's not open for sharing.

Sorry about that!

**Comment by ghost** [comment]
Thank you.
I want to know text file format.

Can I get a same text file?

**Comment by BoPengGit** [comment]
Hi Samjin,

The text file format that was used is just a .txt file with each new line as a new description. So you can use any .txt file or csv text file and run the code. Just replace "open(sys.argv[1]) " with open("your txt file.txt") because sys.argv is when running on the command line.

Thanks and good luck!
